export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';

export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS';

export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES';
export const FETCH_EMPLOYEES_SUCCESS = 'FETCH_EMPLOYEES_SUCCESS';

export const FETCH_EMPLOYEE_DETAILS = 'FETCH_EMPLOYEE_DETAILS';
export const FETCH_EMPLOYEE_DETAILS_SUCCESS = 'FETCH_EMPLOYEE_DETAILS_SUCCESS';
export const UPDATE_EMPLOYEE_DETAILS = 'UPDATE_EMPLOYEE_DETAILS';
export const UPDATE_EMPLOYEE_DETAILS_SUCCESS = 'UPDATE_EMPLOYEE_DETAILS_SUCCESS';

export const FETCH_TOTAL_EMPLOYEES = 'FETCH_TOTAL_EMPLOYEES';
export const FETCH_TOTAL_EMPLOYEES_SUCCESS = 'FETCH_TOTAL_EMPLOYEES_SUCCESS';

export const FETCH_ONLINE_EMPLOYEES = 'FETCH_ONLINE_EMPLOYEES';
export const FETCH_ONLINE_EMPLOYEES_SUCCESS = 'FETCH_ONLINE_EMPLOYEES_SUCCESS';

export const FETCH_ACTIVITIES = 'FETCH_ACTIVITIES';
export const FETCH_ACTIVITIES_SUCCESS = 'FETCH_ACTIVITIES_SUCCESS';
export const SET_VACATIONS = 'SET_VACATIONS';
export const SET_VACATIONS_SUCCESS = 'SET_VACATIONS_SUCCESS';

export const FETCH_VACATIONS = 'FETCH_VACATIONS';
export const FETCH_VACATIONS_SUCCESS = 'FETCH_VACATIONS_SUCCESS';
export const DELETE_VACATION = 'DELETE_VACATION';
export const DELETE_VACATION_SUCCESS = 'DELETE_VACATION_SUCCESS';

export const DEACTIVATE_EMPLOYEE = 'DEACTIVATE_EMPLOYEE';
export const DEACTIVATE_EMPLOYEE_SUCCESS = 'DEACTIVATE_EMPLOYEE_SUCCESS';

export const SEARCH_EMPLOYEE = 'SEARCH_EMPLOYEE';
export const SEARCH_EMPLOYEE_SUCCESS = 'SEARCH_EMPLOYEE_SUCCESS';

export const FETCH_ADMIN_PROFILE = 'FETCH_ADMIN_PROFILE';
export const FETCH_ADMIN_PROFILE_SUCCESS = 'FETCH_ADMIN_PROFILE_SUCCESS';